### PR TITLE
added dim props + padding

### PR DESCRIPTION
**Pull request by achang28**
just a casual attempt at allowing pdf size dimensions to be specified in React Native props.

### CODE REVIEW

**Comment by christopherdro** [comment]
@achang28 Nice! Would you be so kind and add these options inside the Readme file and if possible inside the example project. That would be great!

**Comment by achang28** [comment]
I'll start off with the readme, and if time permits, put up a simple sample.  Stay tuned...

**Comment by christopherdro** [comment]
Yea no worries about the example, readme will be great for now. I can go ahead and update the example  when i get some free time. Thanks again! :)

**Comment by achang28** [comment]
Cool. Btw nice work on getting this up. Very useful

**Comment by christopherdro** [comment]
:+1: Thank you! I ended up creating a native module for AirPrint as well which works really nice.

**Comment by achang28** [comment]
Yes I saw it, and actually am incorporating react-native-print into my
project.

**Pull request merged**
