### PR TITLE
base64 pdf

### PR DESCRIPTION
**Pull request by Nicolas-Menettrier**
Maybe it's more clear if we only return the filePath string if base64 is set to false instead of a NSDictionary containing an empty string for the base64. What is the best solution ?

### CODE REVIEW

**Comment by Nicolas-Menettrier** [comment]
#13

**Comment by neverlan** [comment]
Up :)

**Comment by christopherdro** [comment]
@Nicolas-Menettrier  Thanks for putting this PR together. Any chance this support can be added for android as well?

**Comment by Nicolas-Menettrier** [comment]
I don't know how to do this in java, maybe @parkerdan  can add this features for android too?

**Pull request merged**
