### PR TITLE
Remove example folder and update android build tools gradle.

### PR DESCRIPTION
**Pull request by jeromemmiranda**

### CODE REVIEW

**Comment by christopherdro** [comment]
@jeromemmiranda Why are we removing the example folder?

**Comment by MahbbRah** [comment]
> @jeromemmiranda Why are we removing the example folder?

This one creating issues and won't building the app most of the time so I think it's important to remove the example folder.

**Comment by christopherdro** [comment]
The example folder already appears to be added to https://github.com/christopherdro/react-native-html-to-pdf/blob/master/.npmignore

Is this not the case?

**Comment by christopherdro** [comment]
ping @jeromemmiranda MahbbRah

**Comment by MahbbRah** [comment]
> 
> 
> The example folder already appears to be added to https://github.com/christopherdro/react-native-html-to-pdf/blob/master/.npmignore
> 
> Is this not the case?

Now everything seems fine. we don't have to delete everytime the example folder while building the app. it was real frustrating. 

Thanks for ignoring the example folder :)

**Pull request closed without merging**
