### PR TITLE
Update PdfConverter.java for targetSDK 29

### PR DESCRIPTION
**Pull request by rohitatcoffee**

### CODE REVIEW

**Comment by douglasOlv** [comment]
can u accept this pull request, i realy need this change

**Comment by vitobreda** [comment]
I need this change too, if you can accept this i appreciate

**Comment by relivetech** [comment]
i needed this pull request please accept this

**Comment by Onibenjo** [comment]
Ypu can install from a forked version, here's one:


```yarn add https://github.com/Onibenjo/react-native-html-to-pdf.git```

or

```npm install https://github.com/Onibenjo/react-native-html-to-pdf.git```

**Comment by christopherdro** [comment]
Thanks for the pull request. Closing this one since there was one previously submitted with the same changes that was just merged.

**Pull request closed without merging**
